/* ============================================================================
 * DO NOT EDIT — GENERATED FILE.
 *
 * Generated by scripts/generate_contracts_ts.py from backend/contracts.py
 * (the single source of truth for cross-boundary contracts; payload interfaces
 * derive transitively from rulebook/claim_types_legal_map.json).
 *
 * Regenerate:  python scripts/generate_contracts_ts.py
 * Verify:      python scripts/generate_contracts_ts.py --check
 * ========================================================================= */

/* ----- Enums (string-literal unions) ----- */

export type Product = "personal_loan" | "credit_card" | "mortgage_prequal";

/** Legal-entity taxonomy: each value names the body of law that governs the claim. */
export type ClaimType = "triggering_term" | "rate_or_apr" | "promotional_or_introductory" | "fixed_rate_representation" | "approval_or_prequalification" | "fee_or_cost" | "endorsement_or_testimonial" | "government_affiliation" | "general_udaap_representation";

export type DisclosureType = "apr_qualifier" | "trigger_disclosure" | "soft_pull" | "not_guaranteed" | "opt_out_notice" | "schumer_box_link" | "nmls_id" | "taxes_insurance" | "state_license" | "intro_adjacency" | "other";

export type CheckClass = "legality" | "truthfulness" | "fidelity" | "judgment";

export type Severity = "critical" | "high" | "medium" | "low" | "info";

export type FindingStatus = "open" | "accepted" | "overridden";

export type CheckKind = "deterministic" | "llm_judged";

export type SubmissionMode = "pre_publication" | "verification";

export type BadgeDesignation = "prequalified" | "pre-approved";

export type AuthorityRegime = "statute" | "regulation" | "official_interpretation" | "agency_guide" | "enforcement_doctrine" | "state_statute" | "state_regulation";

/* ----- Models ----- */

/** One marketing claim extracted from an evidence artifact. */
export interface Claim {
  id: string;
  /** Every legal category this statement embodies (amendment #4: one statement = one claim object; a span embodying multiple legal categories lists them all — the old two-objects convention is REPLACED) */
  claim_types: ClaimType[];
  /** Verbatim claim text as rendered */
  text: string;
  /** Where in the artifact (e.g. 'headline', 'fine print', 'badge') */
  location: string;
  source_evidence_id: string;
  /** Amendment #5: union of the payload contracts of every listed claim type — typed per CLAIM_TYPE_PAYLOADS; validate with validate_claim_payload() */
  normalized_fields?: Record<string, unknown>;
}

/** One disclosure found in an evidence artifact. */
export interface Disclosure {
  id: string;
  disclosure_type: DisclosureType;
  text: string;
  location: string;
  /** e.g. 'headline', 'body', 'fine_print', 'below_fold' */
  prominence: string;
}

/** One body of law a rule rests on, with a pinpoint citation. */
export interface LegalAuthority {
  /** Human name, e.g. 'Regulation Z (Truth in Lending Act)' */
  body: string;
  /** Formal pinpoint cite, e.g. '12 CFR § 1026.24(d)(2)' */
  citation: string;
  regime: AuthorityRegime;
  /** CFPB | FTC | state name */
  regulator: string;
  url: string;
}

/** One machine-actionable compliance rule. */
export interface RulebookEntry {
  rule_id: string;
  product: Product;
  /** Claim types this rule subscribes to */
  claim_types: ClaimType[];
  check_kind: CheckKind;
  severity: Severity;
  /** Machine-actionable data: trigger-term lists, required disclosures, phrase lexicon, caps */
  parameters?: Record<string, unknown>;
  /** Authorities this rule operationalizes; primary authority first */
  authorities: LegalAuthority[];
  /** Plain-language rationale, shown to reviewers and fed to the LLM judge */
  explanation: string;
}

/** One row of the offer matrix — the source of truth of what may be claimed. */
export interface OfferCell {
  offer_id: string;
  product: Product;
  offer_name: string;
  apr_min?: number | null;
  apr_max?: number | null;
  apr_type?: string | null;
  term_months?: number | null;
  amount_min?: number | null;
  amount_max?: number | null;
  origination_fee_pct?: string | null;
  fee_deducted_from_proceeds?: boolean | null;
  intro_apr_pct?: number | null;
  intro_period_months?: number | null;
  annual_fee?: number | null;
  badge_designation_allowed: BadgeDesignation;
  is_firm_offer: boolean;
  min_credit_score?: number | null;
  states_excluded?: string[];
  effective_start: string;
  effective_end: string;
  notes?: string;
}

/** One review request: an evidence artifact plus its context bundle. */
export interface Submission {
  id: string;
  submission_id: string;
  partner: string;
  date_submitted: string;
  surface: string;
  product: Product;
  template_id: string;
  template_version: string;
  offer_ids?: string[];
  proposed_headline?: string;
  badge_text?: string;
  dynamic_slots?: string[];
  disclosures_included?: string[];
  asset_files?: string[];
  states_targeted?: string;
  requested_launch?: string | null;
  change_summary?: string;
  status?: string;
  sla_due?: string | null;
  mode?: SubmissionMode;
  /** verification mode: the APPROVED submission this evidence is diffed against (fidelity join key) */
  baseline_submission_id?: string | null;
}

/** One issue (or gray-area flag) raised against a submission. */
export interface Finding {
  id: string;
  check_class: CheckClass;
  severity: Severity;
  rule_id?: string | null;
  claim_id?: string | null;
  summary: string;
  explanation: string;
  citation_url?: string | null;
  suggested_redline?: string | null;
  status?: FindingStatus;
}

/** One execution of the engine against one submission. */
export interface CheckRun {
  id: string;
  submission_id: string;
  rulebook_version: string;
  offer_matrix_version: string;
  mode: SubmissionMode;
  created_at: string;
  findings?: Finding[];
}

/* ----- Claim-type payload interfaces -----
 * Derived from rulebook/claim_types_legal_map.json via
 * backend.contracts.CLAIM_TYPE_PAYLOADS (amendment #5 single source of
 * truth). Field set reflects the map at generation time. ----- */

/** normalized_fields payload for claim type "triggering_term" */
export interface TriggeringTermPayload {
  payment_amount?: number | null;
  num_payments?: number | null;
  term_months?: number | null;
  downpayment?: number | null;
  finance_charge?: number | null;
  downpayment_is_pct?: boolean | null;
}

/** normalized_fields payload for claim type "rate_or_apr" */
export interface RateOrAprPayload {
  value_pct?: number | null;
  range_min_pct?: number | null;
  range_max_pct?: number | null;
  is_floor_claim: boolean;
  labeled_as_apr: boolean;
  rate_kind: "apr" | "interest_rate" | "unlabeled";
}

/** normalized_fields payload for claim type "promotional_or_introductory" */
export interface PromotionalOrIntroductoryPayload {
  promo_rate_pct: number;
  promo_period_months?: number | null;
  has_intro_word: boolean;
  is_deferred_interest: boolean;
  post_promo_rate_stated: boolean;
}

/** normalized_fields payload for claim type "fixed_rate_representation" */
export interface FixedRateRepresentationPayload {
  applies_to_rate: boolean;
  fixed_period_stated?: string | null;
}

/** normalized_fields payload for claim type "approval_or_prequalification" */
export interface ApprovalOrPrequalificationPayload {
  badge_word: string;
  strength: "guaranteed" | "pre_approved" | "prequalified" | "odds_numeric" | "odds_qualitative" | "invitation";
  odds_value_pct?: number | null;
}

/** normalized_fields payload for claim type "fee_or_cost" */
export interface FeeOrCostPayload {
  fee_claim_kind: "absence_of_fee" | "specific_fee_amount" | "fee_disclosure";
  fee_type?: "annual_fee" | "origination_fee" | "closing_costs" | "balance_transfer_fee" | "other" | null;
  amount_value?: number | null;
  amount_is_pct?: boolean | null;
}

/** normalized_fields payload for claim type "endorsement_or_testimonial" */
export interface EndorsementOrTestimonialPayload {
  endorser_named: boolean;
  material_connection_disclosed: boolean;
  atypical_result_claimed: boolean;
  result_claim_text?: string | null;
}

/** normalized_fields payload for claim type "government_affiliation" */
export interface GovernmentAffiliationPayload {
  agency_or_program?: string | null;
  is_program_reference: boolean;
  affiliation_implied: boolean;
}

/** normalized_fields payload for claim type "general_udaap_representation" */
export interface GeneralUdaapRepresentationPayload {
  representation_kind: "urgency_device" | "comparative_superlative" | "amount_offered" | "savings_claim" | "soft_pull_claim" | "debt_elimination" | "geographic_availability" | "other";
  amount_value?: number | null;
  claimed_deadline?: string | null;
  comparative_is_measurable?: boolean | null;
}

/** ClaimType value -> its payload interface. */
export interface ClaimTypePayloads {
  "triggering_term": TriggeringTermPayload;
  "rate_or_apr": RateOrAprPayload;
  "promotional_or_introductory": PromotionalOrIntroductoryPayload;
  "fixed_rate_representation": FixedRateRepresentationPayload;
  "approval_or_prequalification": ApprovalOrPrequalificationPayload;
  "fee_or_cost": FeeOrCostPayload;
  "endorsement_or_testimonial": EndorsementOrTestimonialPayload;
  "government_affiliation": GovernmentAffiliationPayload;
  "general_udaap_representation": GeneralUdaapRepresentationPayload;
}
