#!/usr/bin/env python3
"""Generate frontend/src/contracts.gen.ts from backend/contracts.py.

backend/contracts.py is the single authoring root for cross-boundary shapes;
this script derives the TypeScript mechanically. Never edit the .gen.ts.

    python scripts/generate_contracts_ts.py           # (re)generate
    python scripts/generate_contracts_ts.py --check   # exit 1 if committed file is stale

Deterministic by construction: emission follows enum/model declaration order and
pydantic's insertion-ordered model_fields; the banner carries no timestamps.
Two consecutive runs yield byte-identical output.
"""

from __future__ import annotations

import sys
import types
import typing
from datetime import date, datetime
from enum import Enum
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from pydantic import BaseModel  # noqa: E402

import backend.contracts as contracts  # noqa: E402

OUT_PATH = REPO_ROOT / "frontend" / "src" / "contracts.gen.ts"

BANNER = """\
/* ============================================================================
 * DO NOT EDIT — GENERATED FILE.
 *
 * Generated by scripts/generate_contracts_ts.py from backend/contracts.py
 * (the single source of truth for cross-boundary contracts; payload interfaces
 * derive transitively from rulebook/claim_types_legal_map.json).
 *
 * Regenerate:  python scripts/generate_contracts_ts.py
 * Verify:      python scripts/generate_contracts_ts.py --check
 * ========================================================================= */
"""

_SCALARS = {str: "string", int: "number", float: "number", bool: "boolean",
            date: "string", datetime: "string"}


def _ts_type(ann) -> str:
    """Map a resolved Python annotation to a TypeScript type expression."""
    if ann is type(None):
        return "null"
    origin = typing.get_origin(ann)
    args = typing.get_args(ann)
    if origin is typing.Literal:
        return " | ".join(_quote(v) for v in args)
    if origin in (typing.Union, types.UnionType):
        parts = [_ts_type(a) for a in args]
        seen: list[str] = []
        for p in parts:  # preserve order, drop dupes
            if p not in seen:
                seen.append(p)
        return " | ".join(seen)
    if origin is list:
        inner = _ts_type(args[0]) if args else "unknown"
        return f"{inner}[]" if " " not in inner else f"({inner})[]"
    if origin is dict:
        key = _ts_type(args[0]) if args else "string"
        val = _ts_type(args[1]) if args else "unknown"
        return f"Record<{key}, {val}>"
    if isinstance(ann, type):
        if issubclass(ann, Enum):
            return ann.__name__
        if ann in _SCALARS:
            return _SCALARS[ann]
        if ann is dict:
            return "Record<string, unknown>"
        if ann is list:
            return "unknown[]"
        if issubclass(ann, BaseModel):
            return ann.__name__
    return "unknown"


def _quote(value) -> str:
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _doc_comment(text: str | None, indent: str = "") -> list[str]:
    if not text:
        return []
    first_line = text.strip().splitlines()[0].strip()
    return [f"{indent}/** {first_line} */"]


def _emit_enum(enum_cls: type[Enum]) -> str:
    lines = _doc_comment(enum_cls.__doc__ if enum_cls.__doc__ else None)
    members = " | ".join(_quote(m.value) for m in enum_cls)
    lines.append(f"export type {enum_cls.__name__} = {members};")
    return "\n".join(lines)


def _emit_model(model_cls: type[BaseModel], name: str | None = None,
                extra_doc: str | None = None) -> str:
    name = name or model_cls.__name__
    lines = _doc_comment(extra_doc or model_cls.__doc__)
    lines.append(f"export interface {name} {{")
    for field_name, info in model_cls.model_fields.items():
        for doc in _doc_comment(info.description, indent="  "):
            lines.append(doc)
        # Optional marker iff pydantic does not require the field (has a default).
        marker = "?" if not info.is_required() else ""
        lines.append(f"  {field_name}{marker}: {_ts_type(info.annotation)};")
    lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    module_items = list(vars(contracts).items())
    enums = [v for _, v in module_items
             if isinstance(v, type) and issubclass(v, Enum) and v.__module__ == contracts.__name__]
    models = [v for _, v in module_items
              if isinstance(v, type) and issubclass(v, BaseModel)
              and v.__module__ == contracts.__name__]

    blocks: list[str] = [BANNER]
    blocks.append("/* ----- Enums (string-literal unions) ----- */\n")
    blocks.extend(_emit_enum(e) + "\n" for e in enums)

    blocks.append("/* ----- Models ----- */\n")
    blocks.extend(_emit_model(m) + "\n" for m in models)

    blocks.append(
        "/* ----- Claim-type payload interfaces -----\n"
        " * Derived from rulebook/claim_types_legal_map.json via\n"
        " * backend.contracts.CLAIM_TYPE_PAYLOADS (amendment #5 single source of\n"
        " * truth). Field set reflects the map at generation time. ----- */\n"
    )
    for claim_type in contracts.ClaimType:  # declaration order — deterministic
        payload_model = contracts.CLAIM_TYPE_PAYLOADS[claim_type]
        blocks.append(
            _emit_model(
                payload_model,
                extra_doc=f"normalized_fields payload for claim type \"{claim_type.value}\"",
            )
            + "\n"
        )
    payload_map_entries = "\n".join(
        f"  {_quote(ct.value)}: {contracts.CLAIM_TYPE_PAYLOADS[ct].__name__};"
        for ct in contracts.ClaimType
    )
    blocks.append(
        "/** ClaimType value -> its payload interface. */\n"
        "export interface ClaimTypePayloads {\n" + payload_map_entries + "\n}\n"
    )
    return "\n".join(blocks)


def main() -> int:
    output = generate()
    if "--check" in sys.argv:
        if not OUT_PATH.exists():
            print(f"contracts codegen: {OUT_PATH} is missing — run "
                  f"python scripts/generate_contracts_ts.py", file=sys.stderr)
            return 1
        if OUT_PATH.read_text() != output:
            print("contracts codegen: frontend/src/contracts.gen.ts is STALE relative to "
                  "backend/contracts.py — run python scripts/generate_contracts_ts.py "
                  "and commit the result", file=sys.stderr)
            return 1
        print("contracts.gen.ts is up to date")
        return 0
    OUT_PATH.write_text(output)
    try:
        shown = OUT_PATH.relative_to(REPO_ROOT)
    except ValueError:
        shown = OUT_PATH
    print(f"wrote {shown} ({len(output)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
